# File managed by pluginsync
sudo: true
services:
- docker
language: go
go:
- 1.6.x
- 1.7.x
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  - GLIDE_HOME="${HOME}/.glide"
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=large
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.x
    env: TEST_TYPE=large
  - go: 1.6.x
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: Ll0RxhWGQC60kcxZBX3GpgXB4ywlZ/xtQL5KNpmiihE5Mj0SqzKTF0UKHUaNQygHJCff94tqpvT4vGmRz+uYT4s7Dgoz+OU0vd7y1jH3uweypZrGg5NkjKMNRIHdWsflcSUec9boDGdTGFoAz0M8Af2ea869QCK130BZh3USMVwt+gSwA8/kBzrj5XuCtV97fcwO7kg7LovTzussS+3ttKAJJQ04Wn8gL+1X0ayE04AvWhtocVrD//2RsVUMq2+fIj0qihKuMu/17Vu+dS+NSYUQKrBZTnYZoTxyhnjD+knPmZcCZcABAx6FWnRy2tLfp9ZM+n5ultXJJ2ilqP8WdUHN7GCZyUrrnH+y8gxeUCLIj2WJ1HCEoFZ4fonsUU3RSc41x1gXpGw0oppvzccJbkwDP/C+uLFdCvHvVcU9EZ74T5djNuZybKzB9bFVfpByN3dDQEKkw2tNMIsN1IYnNTBF2LG7vXjKFkojH5cZmzpuHAR0dTppdX4EVDfZZ7b9r5cLGkGwbMT1e54MWvR1szBT7a4cHqJoeo/HMBgyTkzZQvRmZP4lFiZ3dbvD7qw68izm5k9d5GsXdVAftWSHG4POFiDzOthm1QvB83NWsslzGeyeWaZKWzqW4t+YLfWtZ9oxAihMxkT/KNWJX/09pUKI/0t8e+oq1LcbsRTade0=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-iostat
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: Ll0RxhWGQC60kcxZBX3GpgXB4ywlZ/xtQL5KNpmiihE5Mj0SqzKTF0UKHUaNQygHJCff94tqpvT4vGmRz+uYT4s7Dgoz+OU0vd7y1jH3uweypZrGg5NkjKMNRIHdWsflcSUec9boDGdTGFoAz0M8Af2ea869QCK130BZh3USMVwt+gSwA8/kBzrj5XuCtV97fcwO7kg7LovTzussS+3ttKAJJQ04Wn8gL+1X0ayE04AvWhtocVrD//2RsVUMq2+fIj0qihKuMu/17Vu+dS+NSYUQKrBZTnYZoTxyhnjD+knPmZcCZcABAx6FWnRy2tLfp9ZM+n5ultXJJ2ilqP8WdUHN7GCZyUrrnH+y8gxeUCLIj2WJ1HCEoFZ4fonsUU3RSc41x1gXpGw0oppvzccJbkwDP/C+uLFdCvHvVcU9EZ74T5djNuZybKzB9bFVfpByN3dDQEKkw2tNMIsN1IYnNTBF2LG7vXjKFkojH5cZmzpuHAR0dTppdX4EVDfZZ7b9r5cLGkGwbMT1e54MWvR1szBT7a4cHqJoeo/HMBgyTkzZQvRmZP4lFiZ3dbvD7qw68izm5k9d5GsXdVAftWSHG4POFiDzOthm1QvB83NWsslzGeyeWaZKWzqW4t+YLfWtZ9oxAihMxkT/KNWJX/09pUKI/0t8e+oq1LcbsRTade0=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-iostat
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
- provider: releases
  api_key:
    secure: vRyK2BWRRX48FMTP2Jyb0/da5S+ABc8CisX45xtwpSBUlPZkFjJ4+iZvkgbqYt5oZ+WalDAF40zPdr7v+JxNJ/HczCRjitS9S5f5+Nx75kj6ZaWPDESKi4UchVdwq4gS76b0yd1VxBz55j2uHQ2gPILDtVzq+rfDykipgVGqZ3SfbK+0zxN7oObfyB3Zo4WkXTl563SuRMtx5DsokraawN7BlPYuCAcE6BHf3QGCD3J+7Sbn9VUeWjYknpjZceAy/fPTXuSkvdFfU0Vm1GW9Ywsx0CX9BfRMNZjVL+0hC+e+NZN/+F5pDIxZCzZcqKpGPL7f5YZU5fgqn6nyBCHY5Ka5HInJT2EsSzpFVJTtPuuyNV/3+iIGZFrjbM3jLd5abW5C/G3E+8irrAoOgf4vYUKFN1/RE5UiwjRG69eH5aTgAXqRZfULDxgr1aZsIz7xjjXGd34RuQhxN390gVKy+Kubyq62A8J3W0d99FMs2p+EVxblCb6tHWpfDbI2cUzLffw4PNUhTsu7QpTD2kUPf57qzFWn7Wse2v38zLqoMFrWdizSIgNgnauB08ZkFSIBwHSjMi8/WZBC4SGOX63U+6rerJRFOzbODkWrqJQD+ghIvMIcmL1od8cM8/pCXHJbJIMmzN2Ay1PyyzBDsRSRlgXnmZ9I39632jySzDVHg2w=
  file:
    - release/snap-plugin-collector-iostat_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-collector-iostat
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
